### ISSUE TITLE
52131 Invalid APNs credentials

### ISSUE THREAD

**Issue by isayeter** [twilio/voice-quickstart-objc#101]
Hello, When I hit my placeCall.php endpoint, the client did not receive the push notification, and I see an error in Call Logs that says: **52131 Invalid APNs credentials**

I just followed this documentation: https://github.com/twilio/voice-quickstart-objc#8-create-a-push-credential-with-your-voip-service-certificate

I created VOIP certificate and downloaded it : 

![screen shot 2018-04-17 at 15 47 54](https://user-images.githubusercontent.com/3602109/38870508-b815b8ba-4256-11e8-9b77-f8c9681b56be.png)

After that I exported it from KeyChain as .p12 file to my desktop : 

![screen shot 2018-04-17 at 15 48 12](https://user-images.githubusercontent.com/3602109/38870560-d767cfe6-4256-11e8-95fc-274e200f3d50.png)

After that, I executed these commands:

    cd Desktop
    openssl pkcs12 -in Certificates.p12 -nocerts -out key.pem

When I executed this command, it asks me to enter PEM pass phrase, I set it 123123, if I don't set a pass phrase, the next command will not be success. So password is obligatory but the documentation does not say anything about it.

    openssl rsa -in key.pem -out key.pem

It asks me the PEM pass phrase, I enter 123123 and it is done successfully.

    openssl pkcs12 -in Certificates.p12 -clcerts -nokeys -out cert.pem

After this command I have cert.pem and key.pem on the desktop, I copied the contents of them from -----BEGIN CERTIFICATE----- to -----END CERTIFICATE----- part as the documentation says. I saved them on Twilio.

But when I try to place a call I see "52131 Invalid APNs credentials" error, what is wrong?

Thanks.

**Comment by bobiechen-twilio** [comment]
Hi @fattalgazi 

Can you provide us a call sid when this error happened so then we can take a deeper look of what is going on?
In the meantime can you also check if the "sandbox" option is properly configured when creating the Push Credential. The sandbox option must be enabled so that the Twilio Notify service knows to send the notification request to Apple's sandbox endpoint during development stage. Once the app is ready for store submission, you will need another Push Credential which does not have the sandbox option enabled.

Thanks
-bobie

**Comment by isayeter** [comment]
Hello @bchen-twilio , this is the SID : CAd98c7384de316b4f1826c473aad40cb7

And yes I enabled sandbox option.

Thanks.

**Comment by bobiechen-twilio** [comment]
Hi @fattalgazi 

Thanks for providing the Call SID. I did check the Push Credential SID but it seems to be perfectly okay - it's a VoIP certificate and has not expired, and it's also configured for sandbox usage.

Is it possible that the CSR file you used to create this VoIP Certificate, was used to create other certificate before such as a regular APNS certificate?

**Comment by isayeter** [comment]
Thank you for your answer @bchen-twilio .

Yes I am using the same CertificateSigningRequest file for years for different projects, I created VOIP certificate for our other VOIP apps with same CSR file before and they are working normal in those projects. I don't think it is related with CSR file.

**Comment by isayeter** [comment]
oh @bchen-twilio , I solved the problem and received VOIP Push successfully, sorry it was my mistake! 

I created VOIP certificate for ObjCVoiceQuickstart project, but I installed ObjCVoiceCallKitQuickstart project to my phone.

Sorry to bother and thanks for your help.

**Comment by bobiechen-twilio** [comment]
Glad that things are working!

**Comment by benSmith1981** [comment]
Dear BChen, I also have the same issue but with Programmable chat. I replied to this on another thread, so you may see!! https://github.com/twilio/voice-quickstart-swift/issues/142 and here https://stackoverflow.com/questions/51296066/twilio-chat-ios-production-apn-certifications-error-52131

When I test my sandbox APN certifcates the push notifications work perfectly. Project SID: IS5c984ff02c934f2699520f429f2e3a3d

However when I create APN PUSH SERVICES Certification and upload these and link them to my programmable chat function I get the error message: 52131 - Invalid APNs credentials... https://www.twilio.com/console/runtime/debugger/NOf2857a6c1db54e27984dd8fa9ff5100f
My SID for my Production Programmable chat is: IS0f9c58cdde5441feb7eb520aa828df94

Just to clarify, the push notifications work perfectly on my development project SID: IS5c984ff02c934f2699520f429f2e3a3d
I use a Sandbox APN certificate, and selected the Sandbox tick box

However in the production version, where I am using:

Specific APN Apple Push Services Certificate, for a unique APP ID I get the 52131 error.
I did not tick use for sending to Sandbox credential. As it is a push credentiual
I followed all the instructions perfectly for exporting the certificate keys.
I also use separate API Keys and a separate Programmable chat.
I get registration of bindings but no notifications as the certificate is invalid, which I cannot see why it is?
This is the bug https://www.twilio.com/console/runtime/debugger/NOf2857a6c1db54e27984dd8fa9ff5100f
I read in one your replies to a similar issue you said something about not having the Sandbox and PUSH SERVICES APN certificate in the same App ID? Or not using the same CertificateSigningRequest to generate the Sandbox and PUSH? Why would this make a difference can you clarify?
