### ISSUE TITLE
the twilio number can't be used for registting facebook,google or Lyft, why?

### ISSUE THREAD

**Issue by jiananai** [twilio/voice-quickstart-objc#106]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Voice SDK Guides](https://www.twilio.com/docs/api/voice-sdk)
>  * [GitHub Issues](https://github.com/twilio/voice-quickstart-objc/issues)
>  * [Changelog](https://www.twilio.com/docs/api/voice-sdk/ios/changelog)

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```objc
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

[e.g. 2.0.0-beta13 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6s Plus]

**Comment by bobiechen-twilio** [comment]
Hi @jiananai 

I am closing this ticket since it is not related to the Voice SDK. Please go to [Twilio Support](https://support.twilio.com/hc/en-us) and open a support ticket with the question.

Thanks.
