### ISSUE TITLE
Outdated Readme & 52143 - "The push notification was rejected by APNs"

### ISSUE THREAD

**Issue by nxz91** [twilio/voice-quickstart-objc#110]
Hello,

I have the feeling that this Howto is a little dated. The Programmable Voice section in the Twilio Console does not contain a Tools subsection and Push Credentials page anymore. This is now part of the Runtime section (Credentials), correct? When I'm trying to ninja my way through this readme, I also get an error message when doing "$> openssl rsa -in key.pem -out key.pem":

> unable to load Private Key
> 140735489184712:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.50.2/libressl/crypto/pem/pem_lib.c:704:Expecting: ANY PRIVATE KEY

When I follow this guide instead: https://www.twilio.com/docs/notify/configure-ios-push-notifications#action-credentialSID

I get a valid cert.pem and key.pem and add it as a sandbox credential of type APN to the Credentials section under `Runtime`. When I call an existing identity, I get the cryptic error 52143 - "The push notification was rejected by APNs". When I add a random character to the dial.client string, the call correctly aborts because the identity has not been registered.

What am I doing wrong? Is there a bug? And after all, can you update the readme for us? :-)

Thanks!

**Comment by bobiechen-twilio** [comment]
Hi @nxz91 

We are sorry for not updating the quickstart to reflect Twilio console updates. I've already cut tasks and we will update very soon. I believe currently if you want to create/update the mobile push credentials under the Programmable Voice dashboard, it looks like
```
Twilio Developer Console
  - Programmable Voice
    - SDKs
      - Mobile Push Credentials
```

About the error when you are generating the private key, not sure if it is the problem but can you run `openssl version` and let us know what is the version in your env (I am seeing 22.50.2 but not sure)? mine says `LibreSSL 2.2.7` and I've just used the same commands to update the push credential of our internal test app yesterday.

The `52143` error you are seeing when making the call to the client is definitely related to the private key of push credentials. I did a quick search and found [this thread](https://stackoverflow.com/questions/18460035/unable-to-load-private-key-pem-routinespem-read-biono-start-linepem-lib-c6) - maybe this will help resolve our problem?

-bobie

**Comment by nxz91** [comment]
Hi Bobie, thanks for the quick reply! Unfortunately, I keep getting the same error (https://www.twilio.com/docs/api/errors/52143).

Turns out that not specifying a PEM pass phrase (leaving it empty) results in openssl not exporting any key. When I specify something there, I get the encrypted key which I can then turn into an RSA key in the next step. So that part works fine, thanks!

However, the same error comes up again: the phone keeps ringing and in the background, the push notification is rejected by Apple because the topic is incorrect. Why can it be incorrect? Is that related to the bundle identifier?

**Comment by nxz91** [comment]
Tried bundle identifiers in Xcode with and without team prefix. Don't really know what else to try...

**Comment by bobiechen-twilio** [comment]
Hi @nxz91 

Glad to see that we are knocking out some obstacles and making progress!
For the `52143` error, could it be that you didn't check the `sandbox` option while creating the Push Credential SID, while your app is running with development entitlement? (or vice versa)

Based on the sandbox option, Twilio Notify service will send the notification request to different APNS endpoints. The PkPushRegistry device token, which is determined by the entitlement, will be part of the notification delivery request. 

Another possible reason - the CSR file was used somewhere before for creating an APNS certificate.

Let me know if this helps
-bobie

**Comment by nxz91** [comment]
Oh man I don't believe it. Just created a new CSR file and new push credentials and BOOM!

Thanks!!!

**Comment by bobiechen-twilio** [comment]
@nxz91 Nice!

**Comment by bobiechen-twilio** [comment]
Btw, we've updated the outdated screenshots and links of the README. Thanks again for reporting @nxz91!

Cheers
-bobie
