### ISSUE TITLE
Unable to place call from server while <Dial> works

### ISSUE THREAD

**Issue by nxz91** [twilio/voice-quickstart-objc#112]
Hello, me again –

I am successfully establishing a connection between two clients by using TwiML and creating a VoiceResponse with the Dial verb. Now my next task is to make an outbound call to a client.

When I try to reach the same client that I just successfully called from client to client (with TwilioClient.connect) with an outbound call via NodeJS client.calls.create({to: 'client:clientId', from: 'verified phone number', url: 'some other endpoint on my server'}), I get

> "Called is not valid: client:ebcb7183-0385-471e-ba4e-dff91a9cf83b"

What am I doing wrong?

Thanks again!!

**Comment by bobiechen-twilio** [comment]
Hi @nxz91 

Did you mean `callerId is no valid`?
The `makeCall` endpoint in the Node JS example should be able to help you out: https://github.com/twilio/voice-quickstart-server-node/blob/master/src/server.js#L68

Thanks 
-bobie

**Comment by nxz91** [comment]
Hi @bchen-twilio 

Just realized that this is coming from the Twilio server. When I am running Twilio.calls.create() or the below command, I get this error. The error code is 21211 (https://www.twilio.com/docs/errors/21211).

This is the command I ran (with [accountSid], [authToken] and [myVerifiedNumber] replaced):

curl -XPOST https://api.twilio.com/2010-04-01/Accounts/[accountSid]/Calls.json \
    --data-urlencode "Url=https://2c3b0247.ngrok.io/outgoing-call" \
    --data-urlencode "To=client:ebcb7183-0385-471e-ba4e-dff91a9cf83b" \
    --data-urlencode "From=[myVerifiedNumber]" \
    -u '[accountSid]:[authToken]'

Why am I getting this `Called is not valid: client:ebcb7183-0385-471e-ba4e-dff91a9cf83b` ?

When I'm calling directly from the device via TwilioVoice.connect (not from the server), the call is going through. Why doesn't it recognize this identifier when making a server-side outbound call?

Thanks!

**Comment by bobiechen-twilio** [comment]
Hi @nxz91 

Thanks for the clarification.
Now it all comes together and I remember I had the same issue while working on the SDK integration tests - we also use Twilio Client REST APIs to trigger incoming calls to the mobile client and we use `NSUUID` to generate unique IDs for each round of tests, but then realized the `-` in the ID kept failing the REST calls so we had to remove the `-`s from the ID to make the tests happy.

I can confirm that making calls from mobile client to the identity with `-` works fine.

I think the Client REST APIs are still checking if the receiver IDs comply to the [character rules](https://www.twilio.com/docs/voice/client/capability-tokens) - `The client identifier currently may only contain alpha-numeric and underscore characters.`.

For now we would recommend that you use simpler format of callee IDs, at least without `-`s.
Sorry for the inconvenience.

-bobie

**Comment by nxz91** [comment]
Hi @bchen-twilio 

Nice one, problem solved!

 Thanks!!! Have a great one :-)
