### ISSUE TITLE
VOIP Push Notification

### ISSUE THREAD

**Issue by NijaahnandhRV** [twilio/voice-quickstart-objc#115]
Hi,

I tried to call from one device to another device in development mode. From the device I called the call is initiated and it's ringing, but the device I called to is not getting notified about the incoming call. I created the certificate from Apple Push Notification service SSL (Sandbox).

![screen shot 2018-08-10 at 3 24 04 pm](https://user-images.githubusercontent.com/37614736/43951763-8d5efb76-9cb1-11e8-9e34-80257b3966a7.png)

After downloading the certificate, converted to pem file and uploaded it to my twilio console as per the instruction given in this website `https://github.com/twilio/voice-quickstart-objc`. Could anyone help me out with this issue please. In my twilio console the following error is coming.

```
bindingType | "apn"
primaryCorrelationId | "CA60a0598fbe5193cffa97f263ea4ebd77"
bindingSid | "BS31c8acb09e19aeafab35e0e87c35849d"
providerMessageId | "500d45a0-39bd-e5aa-d8c0-395f43ec5dba"
requestId | "RQ84f56db2f8665094e680f5f04b69cb87"
notificationSid | "NT2726a60e8820242d602ed7d32f34b9e4"
module | "APNSBA"
description | "Could not find credentials with the specified Credential SID."
isPassthrough | "false"
deliverySid | "DAb67e6cfbd36fd9e057261b4cd7c20f45"
fromReference | "CR2f122d636d1b517055b0134eb061cae8"
```

**Comment by bobiechen-twilio** [comment]
Hi @NijaahnandhRV 

The README of the quickstart clearly says you should `Create an Apple VoIP Services Certificate for this app`
<img width="770" alt="screen shot 2018-08-10 at 8 45 56 am" src="https://user-images.githubusercontent.com/16326574/43967764-065d3ed0-9c7a-11e8-9d4d-a45e81e4d2d8.png">

**Comment by NijaahnandhRV** [comment]
Hi @bchen-twilio 

1)As we are testing in development mode how can we use production certificate for testing in development mode

2)I have also tried using VoIP certificate and tried calling, I get the same error logged in my twilio console.

**Comment by bobiechen-twilio** [comment]
Hi @NijaahnandhRV 

Apple VoIP Service certificate works for both development and production environment. In the development phase (before the app is deployed for in-house distribution or submitted to App Store), you need a Push Credential SID with the **sandbox** option checked. When the app is ready for production, create a different Push Credential SID (with the same VoIP cert) only this time **without the sandbox option checked**. In your application, you need to programmatically determine whether the app is in production mode by checking the *.entitlements file and put corresponding Push Credential SIDs in the access token.

For the error associated with the Call SID **CA60a0598fbe5193cffa97f263ea4ebd77**, there are a couple of Push Credential SIDs created under the Account SID, but **CR2f122d636d1b517055b0134eb061cae8** isn't one of them. Please make sure that you are using correct credentials in the Access Token. Is it possible that you are mixing credentials between master and sub-accounts?

-bobie

**Comment by rochapablo** [comment]
https://stackoverflow.com/questions/53888958/twilio-incoming-calls-not-working-for-ios
