### ISSUE TITLE
3.0 SDK - Codec choice - Opus, G711 etc

### ISSUE THREAD

**Issue by kieronlawson** [twilio/voice-quickstart-objc#117]
Hi,

We are tracking the new 3.0 release of the mobile SDKs and are curious about this comment in the release notes:
'This is our first WebRTC based release using Chromium WebRTC 57.'

We note that the current version is based around pjsip and as far as I can tell through the pjsip logs it appears that during SDP negotation the Twilio media gateways currently require the use of the G711 codec (a=rtpmap:0 PCMU/8000) which is non-optimal for mobile/wifi networks in particular (QOS configuration notwithstanding).

With the migration to WebRTC does this mean that the Opus codec will now be available and be the preferred/default choice? If so, will we have control over the bitrate, and other codec parameters? 

Cheers
Kieron

**Comment by idelgado** [comment]
Yes, we do plan on adding support for Opus moving forward and we are in the process of enabling this capability in our media infrastructure. We would like to make Opus the default audio codec long-term.

We plan on providing an API that closely resembles [preferAudioCodecs](https://twilio.github.io/twilio-video-android/docs/latest/com/twilio/video/ConnectOptions.Builder.html#preferAudioCodecs-java.util.List-) from the Video SDK which will allow you to prefer a particular codec.

In the case of Programmable Voice we will eventually offer Opus in addition to PCMU. We don't plan on supporting any other audio codecs for the time being.

As for exposing control over bitrate, and other parameters, it's not in our current plans but we're happy to explore doing so in the future. This could be added to each codec class.

I will follow up in this ticket once Opus is available to use.
