### ISSUE TITLE
callInviteReceived returning null on callInvite.state

### ISSUE THREAD

**Issue by lazarvgd** [twilio/voice-quickstart-objc#119]
Hi, I am using Twilio lib for ios app written in objective c. The problem is happening when using voip call following this procedure:

- Alice is calling Bob

- Bob is answering the call and talk with Alice

- Alice hangup, but Bob never receives the end call so CallKit is still displayed and detecting that call is still going on.

the log from twilio lib  is here:
`
2018-08-29 16:46:40.042043+0200  [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 200: OK
2018-08-29 16:46:40.042365+0200 [VERBOSE Twilio] on_call_tsx_state(), state: 4, status_code: 200: OK
2018-08-29 16:46:40.042696+0200 [DEBUG Twilio] Inside on_call_state(), call: 0x1415457c0, internal state: 5
2018-08-29 16:46:40.042773+0200  Inside on_call_state(), PJSIP_INV_STATE_DISCONNECTED, internal state: 5, last_status: 200
2018-08-29 16:46:40.042837+0200 [VERBOSE TVOCall] handlePJSIPInviteStateDisconnected. Error: (null)
2018-08-29 16:46:40.042904+0200 [INFO TVOCall] Inside publishConnectionEvent:, event type: disconnected-by-remote
`

I have observed that method **- (void)callInviteReceived:(TVOCallInvite *)callInvite {** is called and the **callInvite.state** has value **NULL**.

According to the comment in TVONotificationDelegate.h: 

`
/**
 * @name Required Methods
 */

/**
 * @brief Notifies the delegate that a Call Invite was received.
 *
 * @discussion An Invite may be in the `TVOCallInviteStatePending` or `TVOCallInviteStateCanceled` state.
 *
 * @param callInvite A `<TVOCallInvite>` object.
 *
 * @see TVOCallInvite
 */
- (void)callInviteReceived:(nonnull TVOCallInvite *)callInvite;
`

So, the result is my callback for dismissing CallKit is never invoked.
Please keep in mind that I have implemented the lib according to [this](https://github.com/twilio/voice-quickstart-objc) guide and dummy app that is provided.

All this is tested on IPHONE 6s with software 11.4.1 of iOS.
Please let me know if I need to provide additional information and please sorry if omitted something that was required by the template.

**Comment by bobiechen-twilio** [comment]
Hi @lazarvgd 

Thanks for reporting the issue.
It seems odd to me that the `callInvite.state` value you were seeing is `nil`, but apart from that, on Bob side did you get the `call:didDisconnectWithError:` delegate callback when Alice hung up the call? From the log snippet, assuming that's the log of Bob's side, I did see the `disconnect` messages without error.

In the [quickstart](https://github.com/twilio/voice-quickstart-objc/blob/master/ObjCVoiceCallKitQuickstart/ViewController.m#L269), upon receiving the `call:didDisconnectWithError:` callback, the app can then tell CallKit to dismiss the call.

By the way, please feel free and let us know if there is missing feature we should absolutely add to the sample app. Just hoping it's not too dummy.

-bobie

**Comment by lazarvgd** [comment]
Hi, sorry for the delay. I will update this comment with the information that I found.

> but apart from that, on Bob side did you get the call:didDisconnectWithError: delegate callback when Alice hung up the call?

Yes, logs are of Bob's side.
No, no logs about that.

I have implemented that part of the code in this way:
```
- (void)call:(TVOCall *)call didDisconnectWithError:(NSError *)error{
    NSLog(@"TVOCallDelegate didDisconnectWithError:");
    
    if (error) {
        NSLog(@"Call failed: %@", error);
    } else {
        NSLog(@"Call disconnected");
    }
    [self performEndCallActionWithUUID:call.uuid];
    [self callDisconnected];
}

- (void)callDisconnected{
    NSLog(@"TVOCallDelegate callDisconnected");
    self.call = nil;
    self.callKitCompletionCallback = nil;
    self.from = nil;
    
    if(self.delegate && [self.delegate respondsToSelector:@selector(didDisconnectCall)]){
        [self.delegate didDisconnectCall];
    }
}
```

But in the logs there is no log from method **callDisconnected**, nor from call **didDisconnectWithError**

When and what should call method **didDisconnectWithError**?

Non of these lines are shown in the logs.
And you are right, I see that Twilio has detected the end of call, but delegate in never triggered. I have checked that I did not leave some delegates not registered, all looks good.

I have logged the state following this line:
**NSLog(@"## Call should be received : %@",callInvite.state);**
and in logs I have found this:
**## Call should be received : (null)**

One more thing, I have separated Twilio logic from ViewController, and TwilioHelper class is created following this code and registred VIewController as delegate.

```
#pragma mark - Create the Twilio Helper
-(void) createTwilioHelper:(NSString*)targetDevice{
    self.twilioHelper = [[TwilioHelper alloc] init];
    self.twilioHelper.targetDevice = targetDevice;
    self.twilioHelper.delegate = self;
}
```

I cannot post full log due to security reasons, if there is any other way that I can send you the logs, please let me know.

**Comment by bobiechen-twilio** [comment]
Hi @lazarvgd 

For a call to be properly finished on Bob's side, the application should receive the `call:didDisconnectWithError:` delegate callback in this scenario. My hunch is that we should check if the instance that implements the `id<TVOCallDelegate>` is available at the time the call is disconnected by the remote party (Alice).

The `callInvite.state` should not have anything to do with the call not being disconnected properly.

-bobie

**Comment by lazarvgd** [comment]
Hello @bchen-twilio,

Here is my [CallManager](https://pastebin.com/B89TdBMW), which is singleton. And [TwilioHelper](https://pastebin.com/L01GJhmU) that implements TVOCallDelegate. 

ViewController is asking CallManager to make a call, CallManager instantiate TwilioHelper and makes call. So, no weak references. 

Please take a look and let me know if I am missing something?

thanks

**Comment by bobiechen-twilio** [comment]
Hi @lazarvgd 

Please make sure you are passing a valid `TVOCallDelegate` object when making/accepting a call and ensure the lifecycle of the delegate so that the application can receive call state transitions. From the log we did see the call is disconnected and it should also fired the delegate callback to the application.

thanks
-bobie

**Comment by lazarvgd** [comment]
Hi @bchen-twilio 

I have perform intense testing, and I did nothing in code - no changes made, what I found is interesting. I have perform 5 calls in a row, Alice called Bob, Bob answered and Alice ended the call.
In logs I found just one block of messages:
```

TVOCallDelegate didDisconnectWithError:

Call disconnected

TVOCallDelegate callDisconnected
```
So, I can say for sure that all objects are ALIVE and capable to perform action to dismiss the CallKit.

Please can you advice how to solve this problem, we have this code in production.

Thanks,
Lazar

**Comment by bobiechen-twilio** [comment]
Hi @lazarvgd 

Sorry for the delay.
Couple of questions:
- Are you able to connect a call between Alice and Bob and hear audio between two participants?
- Are you able to receive both `callDidConnect:` and `call:didDisconnectWithError:` callbacks, on both side during the lifecycle of the call?

**Comment by bobiechen-twilio** [comment]
Closing the issue for now. Please feel free to re-open or create new issue in the future.
