### ISSUE TITLE
How Can I distinguish getting through from waiting to getting through?

### ISSUE THREAD

**Issue by lyqflnh** [twilio/voice-quickstart-objc#129]
How Can I distinguish getting through from waiting to getting through?

I know when I make a call, delegate method - call:callDidConnect: - will be called, but when the calling is get through, It seem I can not do things when the call is get through.

P.S. I just want to starting a timer when the call is actually getting through instead of connected succeed.

**Comment by bobiechen-twilio** [comment]
Hi @lyqflnh 

If I am understanding correctly, you want to receive the `callDidConnect:` callback only when the call is answered by the callee, right?
There is [a flag called `answerOnBridge`](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) which you can specify in the `<Dial>` verb. The flag is disabled by default. By enabling the flag, the call will stay in `connecting` state and the SDK won't fire the `callDidConnect:` delegate method until the call is answered by the callee.

Hope this helps.
-bobie

**Comment by lyqflnh** [comment]
Two Question Now:

1. Can I distinguish the rejection of callee?

2. About expiration of access token

> The access token generated by your server component is a jwt that contains a grant for Programmable Voice, an identity that you specify, and a time-to-live that sets the lifetime of the generated access token. The default time-to-live is **1 hour** and is configurable up to **24 hours** using the Twilio helper libraries.

> In the iOS SDK the access token is used for the following:
>
> 1. To make an outgoing call via `[TwilioVoice call:params:delegate:]`
> 2. To register or unregister for incoming notifications using VoIP Push Notifications via `[TwilioVoice registerWithAccessToken:deviceToken:completion:]` and `[TwilioVoice unregisterWithAccessToken:deviceToken:completion:]`. Once registered, incoming notifications are handled via a TVOCallInvite where you can choose to accept or reject the invite. When accepting the call an access token is not required. Internally the TVOCallInvite has its own access token that ensures it can connect to our infrastructure.

I think there is unreasonable design here: even I set the access token expiration to 24 hour. I can not assure my app users to open my app every day, and they might miss a call invite.

Take a example:
Bob use my app, and successfully register VoIP Push Notifications via `[TwilioVoice registerWithAccessToken:deviceToken:completion:]`. 
24 hours later, when the token is expired, and Bod didn't reopen my app after the registration, I call Bob. can he get a call invite?

if no, how can I handle this situation?

**Comment by bobiechen-twilio** [comment]
Hi @lyqflnh 

1. Unfortunately the SDK does not (yet) provide the reason as for why the call was disconnected, for example the call was rejected by the callee.
2. The `expiry` in the Access Token only affects when making a call or registering for notification. The mobile client will be able to receive incoming calls unless the app/user explicitly unregisters, or the VoIP certificate itself is invalidated.

-bobie

**Comment by lyqflnh** [comment]
One more question:

How can I get the countryISO of a number when I get the pushKit notification?
`- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(NSString *)type {}`

I can get this `"twi_from" = "+1661XXXX831"` from payload.

I want know is there any way to configure the data in playload from my server.

my purpose is to get countryISO of the caller number.

my problem is I can not do it locally, because:

if I get number like this "+44XXXXX", I can identify the countryCode +44, but I can not know the countryISO, because in my database, countryCode 44 can be countryISO `GG`, `GB` and `VG`.

My APP and server need the countryISO of the number.

**Comment by bobiechen-twilio** [comment]
Hi @lyqflnh 

Although custom push parameters are supported in the TwiML response but the current 2.0 Voice SDK does not provide API to access those values from the SDK objects. You can follow [this guide in the Voice 3.0.0-preview4 changelog](https://www.twilio.com/docs/voice/voip-sdk/ios/3x-changelog#300-preview4-october-2-2018) and add custom parameters when you generate the TwiML response and access the params in the `didReceiveIncomingPushWithPayload` method by looking at the `twi_params` field.

Edit:
The payload of the notification will look like this:
```
aps = {};
"twi_account_sid" = ACXXX;
"twi_bridge_token" = "BRIDGE_TOKEN";
"twi_call_sid" = CAXXX;
"twi_from" = "client:alice";
"twi_message_id" = RUXXX;
"twi_message_type" = "twilio.voice.call";
"twi_params" = "caller_first_name=alice&caller_last_name=smith";
"twi_to" = "client:bob";
```

The custom parameters will be URL-encoded (`caller_first_name=alice&caller_last_name=smith`) so your application has to separate the key-value pairs. 

Let me know if you need further help integrating this feature.

-bobie

**Comment by lyqflnh** [comment]
A call B (NO CALLKIT)
B invoke delegate method `didReceiveIncomingPushWithPayload` two times

I use  following code this to aviod present twice communication page

```obj-c
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(NSString *)type {

    if (_call || _callInvite) {
        return;
    }

    // another code 

}

```

it's working, but when I cancel the calling on A, B will not get into delegate method `didReceiveIncomingPushWithPayload `.

I want to why fire `didReceiveIncomingPushWithPayload ` twice and how can I handle it properly.

Thanks!

**Comment by bobiechen-twilio** [comment]
Hi @lyqflnh,

You should always give the notification payload to the SDK (here:
https://github.com/twilio/voice-quickstart-objc/blob/master/ObjCVoiceQuickstart/ViewController.m#L160)
and you will be notified by the SDK:
- Invite received and pending for answer:
https://github.com/twilio/voice-quickstart-objc/blob/master/ObjCVoiceQuickstart/ViewController.m#L186
- Or invite was canceled:
https://github.com/twilio/voice-quickstart-objc/blob/master/ObjCVoiceQuickstart/ViewController.m#L194

The Programmable Voice service sends both the invite and invite-canceled
notification to all the mobile clients registered with the same identity,
even to the mobile client who accepted the call.

-bobie

On Mon, Nov 5, 2018 at 1:40 AM lyqflnh <notifications@github.com> wrote:

> A call B (NO CALLKIT)
> B invoke delegate method didReceiveIncomingPushWithPayload two times
>
> I use following code this to aviod present twice communication page
>
> - (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(NSString *)type {
>
>     if (_call || _callInvite) {
>         return;
>     }
>
>     // another code
>
> }
>
> it's working, but when I cancel the calling on A, B will not get into
> delegate method didReceiveIncomingPushWithPayload .
>
> I want to why fire didReceiveIncomingPushWithPayload twice and how can I
> handle it properly.
>
> Thanks!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twilio_voice-2Dquickstart-2Dobjc_issues_129-23issuecomment-2D435812431&d=DwMFaQ&c=x_Y1Lz9GyeGp2OvBCa_eow&r=bnRNt8EpUHRCiMPN6oPrCw&m=8ksXfyB8A0lwKVbKvwZxk0-0iyyxqRVHAKHQeR_Q0j0&s=J1EPSy7IijU0q-D85oAxP9UxJ82Vt-EJHdxqQGQxlk0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APkfrngv4RTu-2DS-5FQMgbhzz17k6Tidwntks5usAengaJpZM4X3aar&d=DwMFaQ&c=x_Y1Lz9GyeGp2OvBCa_eow&r=bnRNt8EpUHRCiMPN6oPrCw&m=8ksXfyB8A0lwKVbKvwZxk0-0iyyxqRVHAKHQeR_Q0j0&s=fD2bLc9cryGWjdlVCvX5mvNY19B3GICj0eNctSv_AMA&e=>
> .
>


-- 
[image: twilio] <http://www.twilio.com/?utm_source=email_signature>

**Comment by bobiechen-twilio** [comment]
Hi @lyqflnh 
I am closing this ticket since there hasn't been activity for a while and assuming you are satisfied with the answer. Please feel free to reach to us if you run into any issue or question in the future.

Thanks!
-bobie
