### ISSUE TITLE
Call indicator bar is not responding for audio and video call.

### ISSUE THREAD

**Issue by sojitrajay** [twilio/voice-quickstart-objc#152]
I have implemented voice kit successfully in the application.

I am not able to move in the application from call indicator. Also, I am not able to see green bar on other application screen when user moves from call screen. I have added custom view in navigation bar, but it's not much responsive. 

![Simulator Screen Shot - iPhone XS Max - 2019-03-24 at 20 47 49](https://user-images.githubusercontent.com/3069467/54881593-815de580-4e77-11e9-9596-890a0a8a2fa7.png)

![Simulator Screen Shot - iPhone XS Max - 2019-03-24 at 20 47 43](https://user-images.githubusercontent.com/3069467/54881594-8458d600-4e77-11e9-8572-c86ab17b36b9.png)

I have following doubts for the same.

- Is there any default property which I need to enable to display native call indicator in the application?
- Do I need to put a custom view as I have done? If yes then what will be the best approach to do it?
- Is there any alternative to display custom call indicator inside the application rather than adding view in navigation bar?

**Comment by bobiechen-twilio** [comment]
Hi @sojitrajay 

This is the behavior when integrating the CallKit framework and there is no SDK configuration to hide or disable it.

Thanks,
-bobie

**Comment by sojitrajay** [comment]
@bchen-twilio I am able to move to application from call indicator in background. It was not working on simulator where it did work in the device.

But the question is  why I am not able to see this call bar in the application at the time of ongoing call.

Do you have any reference to working example?

**Comment by bobiechen-twilio** [comment]
Hi @sojitrajay 

It seems to be designed to only show the green status bar to indicate that there is an active call while the VoIP app is in the background.

Thanks
-bobie

**Comment by bobiechen-twilio** [comment]
Closing the issue since this is a system framework design. Feel free to create new issue in the future.
