### ISSUE TITLE
It seems I can not make

### ISSUE THREAD

**Issue by lyqflnh** [twilio/voice-quickstart-objc#158]

**Comment by lyqflnh** [comment]
It seems I can not make a call to China.

Voice call to China will be block .

My app has a great demand in China, any idea how can I enable access.

**Comment by bobiechen-twilio** [comment]
Hi @lyqflnh 

For phone number and geo-permission, please file a [Twilio Support](https://support.twilio.com/hc/en-us) ticket and we can help you from there.

Thanks.
-bobie
