### ISSUE TITLE
Error during sdk registration: error Code: 5

### ISSUE THREAD

**Issue by shubhamgupta-mob-ibtech** [twilio/voice-quickstart-objc#16]
I am using TwilioVoiceClient sdk version 2.0.0-beta5.
I am passing the parameters "AccessToken" and "deviceToken" (Push registry token for Apple VoIP Service) for client registration and getting below error.
[ERROR VoiceClient] Inside register:deviceToken:completion:, failed to register for Twilio push notifications. Error:Failed to register. Code: 5.

**Comment by bobiechen-twilio** [comment]
Hi @shubhamgupta-mob-ibtech,
Bobie here from the iOS SDK team, and I'd like to first thank you for choosing the Twilio Programmable Voice SDK.
Could you share more details about your tokens (both access and device token) and how you generate your access tokens? `Code: 5` usually means the operation failed the authentication, which could be because of invalid credentials in the access token. Please make sure you are using the latest Twilio (server) helper libraries and correct pair of API key & secret.

Thanks.

**Comment by shubhamgupta-mob-ibtech** [comment]
Hi Bobie @bchen-twilio ,
 Thanks for the response. Below are the details to create access token and device token.
 
Testing Environment:-
· Server Twilio SDK Version :- 7.x
. TwilioVoiceClient sdk version 2.0.0-beta5
· Java Version :- Java 8
· OS Version :- iOS 10.1

Device Token:- I have follow the procedure from Get started guidelines to create voip certificate and Twilio Push Credentials for the app.   
To verify the certificate, I have also tested the voip push notifications via “Houston” to our iOS app and successfully able to receive voip push notification on our device.

Access Token:- eyJjdHkiOiJ0d2lsaW8tZnBhO3Y9MSIsInR5cCI6IkpXVCIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJTSzBkZTI0NjlmYTVjZGRiODdiMTA4NzY4YmM5NzZlMzNmIiwiZXhwIjoxNDgzNDM5NzQ5LCJncmFudHMiOnsiaWRlbnRpdHkiOiIyNzE2MzA5MjMyNTI4OTE2NDgiLCJpcF9tZXNzYWdpbmciOnsic2VydmljZV9zaWQiOiJJU2ZmZDE1MTQ5NjA0ZDRmYWU5ZjQyOGIzNTcxMzU3NTkwIiwiZGVwbG95bWVudF9yb2xlX3NpZCI6bnVsbCwiZW5kcG9pbnRfaWQiOiJmb25lYXBwaXBtZXNzYWdpbmc6MjcxNjMwOTIzMjUyODkxNjQ4OjM4QjUxNTIxLTlBRTMtNDI4QS04NEFFLUMzNDBGODA1RUFDQiIsInB1c2hfY3JlZGVudGlhbF9zaWQiOiJDUmE4ZmMwYTcxYzY4MTI4NjlkYjMxMDBiNTA5YjIyMzVkIn19LCJqdGkiOiJTSzBkZTI0NjlmYTVjZGRiODdiMTA4NzY4YmM5NzZlMzNmLTE0ODM0MzYxNjAiLCJzdWIiOiJBQ2UwYWVjZmY2ZGI2OTlkNGJiNjkzOWU1ZThlM2Y1YmVkIn0.6qfr5D9LilW_1QJG9p-Z1NelCtT-4xHUdyx8yjyGDKM

Code snapshot to generate Access Token:-

public String getAccessToken(String userId, String deviceId, DeviceType deviceType, String tokenType) {
        String endpointId = externalCredential.getProperty(TwilioConstants.TWILIO_API_NAME_KEY) + ":" + userId + ":" + deviceId;
        
        IpMessagingGrant grant = new IpMessagingGrant();
        grant.setEndpointId(endpointId);
        grant.setServiceSid(externalCredential.getProperty(TwilioConstants.TWILIO_SERVICE_SID_KEY));
        
        if (DeviceType.ANDROID == deviceType) {
            grant.setPushCredentialSid(externalCredential.getProperty(TwilioConstants.TWILIO_GCM_SID));
        }
        else if (DeviceType.IOS == deviceType) {
          grant.setPushCredentialSid(externalCredential.getProperty(TwilioConstants.TWILIO_APN_CALL_SID));
        }
        AccessToken token =
                new AccessToken.Builder(externalCredential.getProperty(TwilioConstants.TWILIO_ACCOUNT_SID_KEY), 
                  externalCredential.getProperty(TwilioConstants.TWILIO_API_SID_KEY), 
                  externalCredential.getProperty(TwilioConstants.TWILIO_API_SECRET_SID_KEY)).identity(userId).grant(grant).build();
        return token.toJwt();
    }


In case you need more details to analyse  the issue please let me know.

Thanks,
Shubham

**Comment by bobiechen-twilio** [comment]
Hi @shubhamgupta-mob-ibtech,
Thanks for getting back the details. I fed your access token to [jwt.io](jwt.io) and found that the `grant` field is `ip_messaging`, which should be `voice` for the Programmable Voice iOS SDK. Here's the python server sample to use the Twilio helper library to generate the access token with the specific grant for the Voice SDK:
- Import `VoiceGrant` https://github.com/twilio/voice-quickstart-server-python/blob/master/server.py#L3
- Create "Voice" grant https://github.com/twilio/voice-quickstart-server-python/blob/master/server.py#L26

Please let me know if this helps.
Thanks :)

bobie

**Comment by shubhamgupta-mob-ibtech** [comment]
Hi Bobie,
The solution you have suggested works for me. 
Thanks for your help.  :) 
Regards,
Shubham

**Comment by bobiechen-twilio** [comment]
Awesome, Shubham! Glad that helped.
Please feel free to send us any feedback any time in the future.

bobie
