### ISSUE TITLE
Crash on EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by colinyip** [twilio/voice-quickstart-objc#171]
### Description

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000d742d6deb13c

### Steps to Reproduce

I am not able to reproduce it locally, but it happened in our production app.

#### Logs

Please see the following example crash logs from firebase:

```
Crashed: Thread
Crashed: MediaFactoryImpl::signaling
0  TwilioVoice                    0x101315c78 _hidden#14368_ + 2758444
1  TwilioVoice                    0x1012ef3e0 _hidden#14368_ + 2600596
2  TwilioVoice                    0x100f4e7e4 twilio::media::FineAudioBuffer::deliverRecordedData(signed char const*, unsigned long, int, int) + 357028
3  TwilioVoice                    0x100f58494 twilio::media::FineAudioBuffer::deliverRecordedData(signed char const*, unsigned long, int, int) + 397140
4  TwilioVoice                    0x100f6eee0 twilio::media::FineAudioBuffer::deliverRecordedData(signed char const*, unsigned long, int, int) + 489888
5  TwilioVoice                    0x100f6ee5c twilio::media::FineAudioBuffer::deliverRecordedData(signed char const*, unsigned long, int, int) + 489756
6  libsystem_pthread.dylib        0x18cdb42c0 _pthread_body + 128
7  libsystem_pthread.dylib        0x18cdb4220 _pthread_start + 44
8  libsystem_pthread.dylib        0x18cdb7cdc thread_start + 4
```

#### Voice iOS SDK

3.0.0

#### iOS Version

iOS 12.2.0

#### iOS Device

iPhone 6

**Comment by colinyip** [comment]
any update for this issue? @bchen-twilio  

Thanks! 😄

**Comment by bobiechen-twilio** [comment]
Hi @colinyip 

Sorry for not responding back to you sooner.
Thanks for providing the crash and it seems like there is some custom audio device implementation in your application.
- Is it possible to tell (from the application/SDK log) what exactly is the action that the application was performing when the crash happened?
- Can you share some implementation details around the audio device in your application?
- It would be great if you can enable the logging for the WebRTC module by
```
  [TwilioVoice setLogLevel:TVOLogLevelTrace module:TVOLogModuleWebRTC];
```

Thanks,
-bobie

**Comment by perlasivakrishna** [comment]
Same here happening in production Build.

**Comment by bobiechen-twilio** [comment]
Hi @perlasivakrishna 

Can you provide the SDK version and more details such as steps to reproduce, SDK log and the crash stacktrace?

Thanks,
-bobie

**Comment by perlasivakrishna** [comment]
@bchen-twilio  I'm using TwilioVideo 2.10.2, Crash is happened in production Build. After pod update no crashes happened. here is the crash logs.
[crashlog copy.txt](https://github.com/twilio/voice-quickstart-objc/files/3807274/crashlog.copy.txt)

**Comment by bobiechen-twilio** [comment]
Hi @perlasivakrishna 

Thanks for getting back and providing the log. Please file a new issue in the Video iOS SDK repository so that the Video SDK team can take a look: https://github.com/twilio/twilio-video-ios/issues

Cheers,
-bobie

**Comment by perlasivakrishna** [comment]
@bchen-twilio 
👍
