### ISSUE TITLE
iOS 13 Incoming Call VOIP notification doesn't fired when app is on background or phone locked.

### ISSUE THREAD

**Issue by newMobileStar** [twilio/voice-quickstart-objc#188]
Hi, Twilio team

I am very pleased to work with Twilio Voice and Video SDKs. I recently upgraded Voice SDK to version 5.0.0 and It doesn't work properly.

In detail, When the app is on the foreground, It works well, but when the app is on background or phone is locked status, the incoming VOIP push notification doesn't fire.
My device is iOS 13.
With the previous iOS SDK versions, It was working well even when the app is on foreground or background.

- Is this related to the Apple's PushKit VOIP notification policy for iOS 13.+? or Is this an issue on my side?
- Are you using still iOS VOIP notification to handle Twilio Voice Call Invite or Reject actions?

Our app surely needs to work properly even when the app is on the background.

Please give me a solution for this issue asap.

Thanks

**Comment by bobiechen-twilio** [comment]
Hi @newMobileStar 

With the new PushKit policy introduced in iOS 13, apps are required to make some adjustments in order to ensure the incoming capability is not affected whether the apps are active, in the background or terminated. We have also updated our quickstart samples so that they work properly in these scenarios.

Please refer to the [iOS 13 migration guide](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md) for more details.

Starting from the 2.1.0/5.0.0 Voice iOS SDK, the SDK will only subscribe to the "call" notifications and will use a connection to monitor for cancellation internally.

Please provide the Twilio Call SIDs where you are experiencing problems with incoming calls when the app is not in the active state if it is still happening with the quickstart updates in your environment. We can use the Call SIDs to better debug and see if there is any issue.

Thanks,
-bobie

**Comment by newMobileStar** [comment]
Hi @bchen-twilio 

Thanks for your reply!

I just checked the app by uninstalling/reinstalling the app again. Yes, the app receive the VOIP push when the app is on the background. but when the app is on background and receive the VOIP push, the app is killed by this reason:

> - "Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP callback"

And after 3 times try with this issue, the app is not allowed to receive VOIP push anymore. I think this is the current PushKit policy on iOS 13 from Apple.
They say this:

>  "Repeatedly failing to report calls may prevent your app from receiving any more incoming call notifications."

So I think the app have to report incoming call screen of CallKit immediately without any delay  once the app receive the VOIP push from Twilio.
But as you know, when we use Twilio VOICE SDK, we use this handle function and delegate methods.
```
if (![TwilioVoice handleNotification:payload.dictionaryPayload delegate:self delegateQueue:nil]) {
                NSLog(@"This is not a valid Twilio Voice notification.");
            }
```
```
- (void)callInviteReceived:(TVOCallInvite *)callInvite {
    NSLog(@"callInviteReceived:");
    .....
}
- (void)cancelledCallInviteReceived:(TVOCancelledCallInvite *)cancelledCallInvite error:(NSError *)error{
    .....
}
```

My question is:
- Is there any time delay between the handle function and delegate functions?
- when I use the microphone permission request or checking code in the delegate functions, are you sure there will be any time delay for sure?
- Is my idea right?

**Comment by bobiechen-twilio** [comment]
Hi @newMobileStar 

The `TwilioVoice.handleNotification()` method returns a Call Invite object synchronously via the `TVONotificationDelegate` if a valid Call notification is received. The application is responsible of reporting the VoIP push to CallKit as a new incoming call in the `callInviteReceived:` callback method.

The microphone permission should only happen after the call has been reported to CallKit so it will not be a problem.

-bobie

**Comment by newMobileStar** [comment]
Hi @bchen-twilio 

this is my code in the `callInviteReceived:`. 

```
- (void)callInviteReceived:(TVOCallInvite *)callInvite {
    NSLog(@"callInviteReceived:");
    if ([FCVoiceCallManager sharedInstance].callInvite) {
        NSLog(@"A CallInvite is already in progress. Ignoring the incoming CallInvite from %@", callInvite.from);
        if ([[NSProcessInfo processInfo] operatingSystemVersion].majorVersion < 13) {
            [self incomingPushHandled];
        }
        return;
    } else if ([FCVoiceCallManager sharedInstance].call) {
        NSLog(@"Already an active call. Ignoring the incoming CallInvite from %@", callInvite.from);
        if ([[NSProcessInfo processInfo] operatingSystemVersion].majorVersion < 13) {
            [self incomingPushHandled];
        }
        return;
    }
    [FCVoiceCallManager sharedInstance].callInvite = callInvite;
    UIBackgroundRefreshStatus status = [[UIApplication sharedApplication] backgroundRefreshStatus];
    if ([[UIApplication sharedApplication] isRegisteredForRemoteNotifications] && status == UIBackgroundRefreshStatusAvailable) {
        // Allow microphone
        if ([[AVAudioSession sharedInstance] recordPermission] == AVAudioSessionRecordPermissionGranted) {
            NSLog(@"Audio permission granted");
            dispatch_async(dispatch_get_main_queue(), ^{
                [[FCVoiceCallManager sharedInstance] reportIncomingCallFrom:[callInvite.from stringByReplacingOccurrencesOfString:@"client:" withString:@""] withUUID:callInvite.uuid withCustomParamaters:callInvite.customParameters];
            });
        }else if([[AVAudioSession sharedInstance] recordPermission] == AVAudioSessionRecordPermissionUndetermined){
            [[AVAudioSession sharedInstance] requestRecordPermission:^(BOOL granted) {
                if (granted) {
                    NSLog(@"Audio permission granted");
                    dispatch_async(dispatch_get_main_queue(), ^{
                        [[FCVoiceCallManager sharedInstance] reportIncomingCallFrom:[callInvite.from stringByReplacingOccurrencesOfString:@"client:" withString:@""] withUUID:callInvite.uuid withCustomParamaters:callInvite.customParameters];
                    });
                } else {
                    NSLog(@"Audio permission denied");
                }
            }];
        }
    }
}
```

As you see, the CallKit reporting happens after the audio permission check. Is this a problem or not?
Can you please say what is the problem in this code?

**Comment by bobiechen-twilio** [comment]
Hi @newMobileStar 

Thanks for providing the code snippet.
I would recommend moving the mic permission code outside of this callback since it looks like audio input is a must. The mic permission could be granted asynchronously and then the call is reported to CallKit. This will break the PushKit policy and cause the app to be terminated as you observed.

-bobie

**Comment by newMobileStar** [comment]
Hi @bchen-twilio 

Thanks for your answer! I will try and get back to you with the result.

**Comment by newMobileStar** [comment]
I have another question.

We are also using Twilio Video SDK. and we use our VOIP push notification to handle the Incoming Video Call and something more.
According to the iOS 13 PushKit Policy, we should not use VOIP push anymore to handle the incoming Video Call ?
or do you have any suggestion to implement incoming video call notification when app is on background?

**Comment by bobiechen-twilio** [comment]
Hi @newMobileStar 

Reporting incoming video calls is totally the correct thing to do since CallKit also supports video. Just make sure the reporting happens before it goes out of the incoming-push-received callback.
(Wow Programmable Video & Voice SDKs!)

-bobie

**Comment by newMobileStar** [comment]
We are not going to use CallKit for Video SDKs with some reason. So I am asking any suggestion to handle incoming video calls without CallKit.

do you have any recommendations or suggestions for that?

**Comment by bobiechen-twilio** [comment]
Since I am not the expert of the Video SDK so I would suggest asking the question in the Video repository to get a better response. Regular APNS notification might not be as powerful as PushKit pushes in the situation but I think that's one way to invite another client to join the video room.

**Comment by newMobileStar** [comment]
Ok, no problem. Thanks for your support !

**Comment by newMobileStar** [comment]
Btw, I have changed my code by moving the audio record permission code after reporting CallKit.

It's working well. :)

Thank you!

**Comment by bobiechen-twilio** [comment]
Glad to know!
I'll let you close the ticket in case you still need to discuss any other issue.

Cheers,
-bobie
