### ISSUE TITLE
Error while doing outgoing calls Code=31000

### ISSUE THREAD

**Issue by shubhamgupta-mob-ibtech** [twilio/voice-quickstart-objc#19]
I am using TwilioVoiceClient sdk version 2.0.0-beta5.
I am getting the below error while doing the outgoing calls.

Error Domain=TwilioServicesErrorDomain Code=31000 "Twilio Services Error" UserInfo=0x17913d90 {NSLocalizedDescription=Twilio Services Error}

The error occurs when i put the application in the background for long time (approx. 1 hour) and try to do the outgoing calls.
I Think this might be the issue of access token expire.
Please help me out !

**Comment by bobiechen-twilio** [comment]
Hi @shubhamgupta-mob-ibtech 
Thanks for using the SDK and we are glad that you came to us immediately with this issue.
I am sorry that the error message didn't provide much information but it definitely looks like that the token has expired.
I am guessing that you are using the server sample quickstart we provided and yes, the default token expiry of the Twilio helper library is **one hour**. For security reason, the max duration you can specify is up to 24 hours and eventually the token will expire and for the same reason the SDK does not keep track of the token contents but simply use it as the way for Twilio service authentication so (unfortunately) it is the application's responsibility to provide valid access tokens. Currently we are suggesting developers to use the JWT library to decode the token and check if it is still valid before making outgoing calls or alternatively you can generate a 24-hr token and cache it in the **NSUserDefaults**. Still the SDK is still counting on the applications to provide valid access tokens.

Sorry for the long explanation but please let us know if this helps. Thanks.

- bobie

**Comment by shubhamgupta-mob-ibtech** [comment]
Hi Bobie,
The solution you have suggested help me a lot. I will go for JWT library to check token validity before making outgoing calls.
Thanks for your help.

Shubham

**Comment by bobiechen-twilio** [comment]
Hi @shubhamgupta-mob-ibtech,
I am glad it helped. Please don't hesitate to let us know if you run into any issue in the future and we look forward to seeing your awesome Voice app!

**Comment by gerchicov-bp** [comment]
@bchen-twilio hello
Is it correct to rerequest a new access token before each outgoing call?

**Comment by bobiechen-twilio** [comment]
Hi @gerchicov-bp 

This is a good question.
Not exactly. The Access Token is used for authentication purpose when every time calling `TwilioVoice.call()` or `TwilioVoice.un/register()`. The longest token `ttl` allowed by Twilio is 24 hours. If for some reason, e.g. user experience, that fetching new access token every time is not a idea, the application can keep it in the local storage and reuse it as long as it has not expired.

-bobie
