### ISSUE TITLE
Unable to find pod spec

### ISSUE THREAD

**Issue by leejms** [twilio/voice-quickstart-objc#41]
Fresh clone then `pod install`

```
Analyzing dependencies
[!] Unable to find a specification for `TwilioVoice (= 2.0.0-beta11)`
```

I am having this same issue on my custom project

**Comment by bobiechen-twilio** [comment]
Hi @leejms 

For 3rd party podspec host (like the way we are hosting for the Voice SDK beta) you have to run `pod repo update` to let the Cocoapods library fetch the latest.

-bobie

**Comment by leejms** [comment]
Thank you SO MUCH!  worked great.

**Comment by bobiechen-twilio** [comment]
👍  👍  👍
