### ISSUE TITLE
Outgoing Call ending after 4s

### ISSUE THREAD

**Issue by homanp** [twilio/voice-quickstart-objc#5]
Hi,

Stumbled upon another bug. Outgoing calls fail after 4s.

Attached VoiceClient logs.

Any ideas @bchen-twilio?

[\- (2).txt](https://github.com/twilio/voice-quickstart-objc/files/512049/-.2.txt)

**Comment by homanp** [comment]
Turned out to be a client side issue when we integrated CallKit @bchen-twilio.

Closing this!

**Comment by bobiechen-twilio** [comment]
Hi @homanp,
I was checking the log and was about to reply the thread.
But anyway, glad you figured it out 👍

**Comment by homanp** [comment]
Thanks @bchen-twilio! And again, good work 👍

**Comment by homanp** [comment]
BTW, @bchen-twilio. Seems like we can't hear the "ringing"-tone when doing outbound calls with callkit. Any ideas on that?

**Comment by bobiechen-twilio** [comment]
Hi @homanp,
Unlike the 1.2 Client SDK, the new Voice SDK doesn't play ringtones anymore. We are giving the power of ringtone playback back to the applications.

**Comment by homanp** [comment]
Oh, I was talking about the "beep beep" sound the caller hears until the receiver answers. I hear it in my simulator but not on the device.

My guess is it has something to do with CallKit since that doesn't run on the sim.

Any suggestions?

**Comment by bobiechen-twilio** [comment]
I agree. This could be that beta2 (without the audio session handling methods) is not happily cooperating with CallKit. Could you share more detailed steps about how you reproduce the issue so we can also give it a try and see if this is solved in the next beta-to-come?
Thanks.

**Comment by homanp** [comment]
@bchen-twilio I'll create another Issue with examples.
