### ISSUE TITLE
Re-connecting calls after long network interruption

### ISSUE THREAD

**Issue by nicolettemanas** [twilio/voice-quickstart-objc#64]
Hi Twilio team,

This is more of a question rather than an issue. I tried disconnecting both parties of an ongoing call from the internet, wait for five minutes, then reconnect both of the devices to the internet. The call is not reconnecting and neither of the users received disconnection notifications even after one of them hangs up.

We are not disconnecting the call upon network interruption because we know that Twilio tries to reconnect them after a while. However, it seems that when left disconnected for five minutes or longer, the reconnection fails. 

Should we expect a disconnection notification from Twilio after getting back the connection? Or are we suppose to handle this on our side? If so, is it safe to assume that the time out for reconnection is five minutes? 

Thanks!

**Comment by bobiechen-twilio** [comment]
Hi @nicolettemanas 

This is actually a good question and kudos to the experiment and observation!
The Twilio Voice service actually use the `RTP Timeout` the detect this kind of anomaly for the connections - if unfortunately the mobile client loses the network connectivity and stops sending audio packets, the Voice service will kill the connection after certain amount of time. Currently the timeout is exactly 300 seconds, which matches what you observed.

We are actually working actively on adding the `hold()` function to the `TVOCall` object so whenever needed, for example PSTN interruption or CallKit hold-and-answer, the application can tell the SDK to hold the call and unhold it later once the the interruption ends.

-bobie

**Comment by nicolettemanas** [comment]
Thanks @bchen-twilio , given those, I assume that we will not be able to identify that the voice call has been dropped upon reconnecting to the network? Or is there a way to inform the client about the dropped call? 

-Jean

**Comment by bobiechen-twilio** [comment]
Hi Jean,

This is another good question, but unfortunately the mobile client that lost network connection won't be aware of the call being disconnected and won't know why the call was dropped (disconnected by Twilio Voice service). Currently you can only find this out by going to the [Programmable Voice console](https://www.twilio.com/console/voice/dashboard), which is not accessible for app end users.

-bobie

**Comment by nicolettemanas** [comment]
I see. We just have to let it be for now. Thank you for answering! Will close this now. 😄
