### ISSUE TITLE
[TwilioVoice stopAudio]; then [TwilioVoice startAudio]; does not restart call audio

### ISSUE THREAD

**Issue by lisbakke** [twilio/voice-quickstart-objc#67]
### Description

I'm trying to stop the audio session and restart it while in the middle of the call. The use case is to allow the user to use iOS Speech API (Speech/Speech.h) to input audio and then restart the call audio when they are done.

### Steps to Reproduce

1. Initiate a call
2. Call [TwilioVoice stopAudio]
3. Call [TwilioVoice startAudio]
4. You will not get audio back again.

#### Expected Behavior

I expect to re-gain audio from an ongoing call after calling `stopAudio` and then `startAudio`

#### Actual Behavior

Audio does not restart.

#### Reproduces How Often

100%

#### Logs

```
2017-11-03 11:54:31.943698-0400 Ninja[20130:4818322] PJSIP(4):    pjsua_aud.c !.Closing iPhone IO device sound playback device and iPhone IO device sound capture device
2017-11-03 11:54:32.267321-0400 Ninja[20130:4818322] PJSIP(4): coreaudio_dev.  .core audio stream stopped
2017-11-03 11:54:32.270421-0400 Ninja[20130:4818322] (My Log Line) stop audio
2017-11-03 11:54:37.271669-0400 Ninja[20130:4818322] (My Log Line) start audio
// No logs happen after calling startAudio
```

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

2.0.0-beta19 via CocoaPods

#### Xcode

9.0.1

#### iOS Version

11.0.3

#### iOS Device

iPhone 6+

**Comment by lisbakke** [comment]
In my specific case I think I can do what I need to do by sharing the `AVAudioSession` with Twilio. I'll leave this here, though, in case you guys want to recommend a better approach.

**Comment by bobiechen-twilio** [comment]
Hi @lisbakke 

I apologize for my delay of responding back to you.
Currently these methods are designed specifically for CallKit integration. We understand that they may sometimes cause developers confusion and we are actively reviewing the APIs and trying to improve the SDK to provide users the best integration experience. For now we can only suggest you to not use the CallKitIntegration methods outside of CallKit scenarios.

Thanks
-bobie

**Comment by bobiechen-twilio** [comment]
Hi @lisbakke 

We've made some API updates since beta19 around this surface area. Could you use the latest GA version of the Voice SDK and see if the new `TwilioVoice.audioEnabled` property makes sense for you. The quickstart should demonstrate how and when to properly use the flag.

I am closing this issue for now but please feel free to contact us if you run into any issue with the latest version.

Thanks.
-bobie
