### ISSUE TITLE
Can't upload app with TwilioClient pod to App Store

### ISSUE THREAD

**Issue by homanp** [twilio/voice-quickstart-objc#8]
Hi,

Seems as though I can't upload a build with this version of the TwilioClient to the App Store. Any ideas why?

Getting: Code object is not signed at all

**Comment by homanp** [comment]
Is there anything special I need to do to get it to work?

**Comment by homanp** [comment]
Issue is that Apple requires the .sh files to be codesigned as well. Thus one needs to manually remove this file in IPA.

**Comment by bobiechen-twilio** [comment]
Hi @homanp,
Sorry for your inconvenience. We realized that the `strip_archs.sh` was poisoning codesigning and we've worked this out and the solution will be included in the next beta.
Unfortunately this simator-symbol-removing process is still required when you manually drag `TwilioVoiceClient.framework` into app project's Embedded Framework(Binaries) place unless you install the framework via Cocoapods and let it take care of stripping simu-archs when building the app package.

**Comment by homanp** [comment]
Yeah! I actaully Didn't drag n' drop it. Installed through Cocoapods!

**Comment by bobiechen-twilio** [comment]
Awesome. Looking forward to seeing your awesome apps!
And just FYI, last week the app we submitted to the App Store to make sure the SDK conforms to 's guideline got approved.

**Comment by homanp** [comment]
Yeah, really like the stuff you guys are making. Our app is in review at the moment

**Comment by paynerc** [comment]
@homanp Just an FYI that `2.0.0-beta3` has been released and it has the fix to the removal script for the signing issue.

**Comment by homanp** [comment]
Wow, Awesome! Is there any changelog I could view?

**Comment by girtis** [comment]
@homanp of course - the changelog is at https://www.twilio.com/docs/api/voice-sdk/ios/changelog#200-beta3!

**Comment by homanp** [comment]
@girtis Seems as though I can't install the beta3 through cocoapods. `Getting Unable to satisfy the following requirements`. Anything else I must do?

**Comment by paynerc** [comment]
Have you tried doing a `pod update`? That should kick it off to pull the latest from out git repo. Let me know if that doesn't solve it for you.
