### ISSUE TITLE
Empty credentials seen on the console web debugger

### ISSUE THREAD

**Issue by fabriziomoscon** [twilio/voice-quickstart-objc#80]
### Description

When making a call from iOS (2.0.0-beta15) I saw errors in the debugger console regarding Empty credentials, but the relative `credential_sid` doesn't appear to be registered to my account_sid.
For example `DEBUG EVENT SID NO8475c2d5451f4413803070a35550d28e`.
The call is delivered as expected regardless of the error events in the debugger

- Is there any way to remove old and expired credentials?
- are this credentials generated for each new device app installation?

<img width="1439" alt="screen shot 2018-02-08 at 16 30 46" src="https://user-images.githubusercontent.com/721890/35985304-423712e4-0cee-11e8-9ef4-832b901001a6.png">

#### Voice iOS SDK

2.0.0-beta15 via CocoaPods

#### Xcode

9.2

#### iOS Version

11.2

#### iOS Device
Simulator iPhoneX

Also reported in this issue: https://github.com/hoxfon/react-native-twilio-programmable-voice/issues/65

**Comment by bobiechen-twilio** [comment]
Hi @fabriziomoscon 

1. Is there any way to remove old and expired credentials?
  > Yes, you can manage your Push Credentials in the Twilio developer portal.
2. Are this credentials generated for each new device app installation?
  > Push Credentials are tied to applications and you only need one Push Credential SID for this iOS application on every device.

For the `52161 Empty Credential` error, it looks like, as you mentioned, an old Push Credential SID is used when calling the registration method. Please update the Push Credential SID or any other credential in the Access Token whenever you make any update to your account.

The devices can still receive call notification most likely because they were registered with the same identity before and never unregistered.

Thanks.
-bobie

**Comment by fabriziomoscon** [comment]
Hi @bchen-twilio,
I thought they were old credentials as well. But I am not sure how is it possible for the client to register multiple ones for a single session.
Also using the developer portal I can only see 1 APN credential for my account Sid. And the new credentials Sid is used to initiate the session.
Is there any chance that somehow twilio is using the old credentials as well as the be one?
> Please update the Push Credential SID or any other credential in the Access Token whenever you make any update to your account.
Could you elaborate on this point please?

**Comment by bobiechen-twilio** [comment]
Hi @fabriziomoscon 

Thanks for getting back with more details.
As long as the application is always using the latest credentials then everything is good and Twilio will also be using the correct credentials provided in your Access Token.

**Comment by bobiechen-twilio** [comment]
Hi @fabriziomoscon 

I am assuming my comments answered your question and we can close this issue for now. If you are still seeing the same error (empty credential) and the current Push Credential SID is not the one being used, please make sure that the Access Token has the correct credentials or we can ask the Twilio Notify team to check their service DB and see if there is any dead registration bindings.

Thanks!

**Comment by fabriziomoscon** [comment]
I have lots of subaccounts for customers and it seems that only users that have credentials for ios and android have this issue.
The calls get delivered but there are multiple errors in the Debugger as per screenshot.

**Comment by bobiechen-twilio** [comment]
Hi @fabriziomoscon 

I see.
Technically the Access Token server endpoint should be taking care of vending proper Push Credential and other credentials back to the mobile clients based on the platform and user information that come along with the HTTP request.
By the way what are the errors you are seeing in the console?

**Comment by fabriziomoscon** [comment]
After each call I can see many errors divided in 2 groups:
- Error - 52161 Empty Credentials
- Error - 52134 Invalid APNs device token

as per original screenshot

**Comment by bobiechen-twilio** [comment]
You can send the Account SID and Push Credential SID (or just the whole Access Token) to my work email address and I can help you take a look if the credentials are good, but basically these errors mean
- Credential does not exist
- Not from a valid VoIP Service certificate

**Comment by fabriziomoscon** [comment]
Hi Bobie, I have some important updates on this issue. I had to renew my VOIP certificate on Apple dev portal and afterwards I created new Voice credentials using the API. I noticed that my code was old - still calling `https://ip-messaging.twilio.com`, so I change that to `https://notify.twilio.com`.

Is that the new API? Creating a notify credential is the same as creating a voice credential?

I suspect that all my old credentials were created under the old `ip-messaging` namespace and for some fallback mechanism, still be able to be used, I realised they are the same as notify. In fact 3 API URL work as the same:
```
https://notify.twilio.com/v1/Credentials/
https://chat.twilio.com/v1/Credentials/
https://ip-messaging.twilio.com/v1/Credentials/
```

The following credentials SID return errors in console, but are not present under the account, and 
return the following error: `Credential (certificate and private key) is invalid. Certificate expired.`
CRb9d218685af00a485c7411e32a295727
CRe646f5bf4db89463faae91e3665a6390
CR7a6db074716ef1a368510e9178336f31

The following are giving the error `Empty Credentials`:
CRc944458185cedabd3faf0b70e712167d
CR5a36ada842e3b69265bd8999b80d28f6
CR3b0ab20429487c4e4800d0a0054b2be8

I would be great if there were a way to clear that completely from your side, because I have no way to clear them from my side.

Note: please consider these credentials_SID as old so not bound to a PII related

**Comment by bobiechen-twilio** [comment]
Hi @fabriziomoscon 

I am afraid I can't provide much help about managing notification bindings/credentials issue using the Twilio Notify APIs. We do plan to provide credential/binding management self-service under the Programmable Voice dashboard, but for this to be resolved quickly, I'd suggest you go to Twilio Support and ask them to purge old credentials with Notify team's help.

Sorry for the inconveniences.
-bobie
