### ISSUE TITLE
TVOCallDelegate didDisconnectWithError UUID not found

### ISSUE THREAD

**Issue by ariveraati** [twilio/voice-quickstart-objc#89]
### Description

If an incoming call is received while the app is in the background, or the device is off, and it is answered, the didDisconnectWithError is not fired if the incoming caller ends the call. 

### Steps to Reproduce

1. Run the CallKit enabled demo
2. Place the app into the background (home button) or turn off the screen
3. Call the Twilio phone number
4. Answer the call that appears in CallKit
5. End the call on the caller side
6. Observe that the CallKit call does not end and remains open, but silent because the caller is no longer on the line

#### Code

```objc
@interface TwilioVoicePlugin () <PKPushRegistryDelegate, TVOCallDelegate, TVONotificationDelegate, CXProviderDelegate>

[self.callKitProvider setDelegate:self queue:nil];

- (void)call:(TVOCall *)call didDisconnectWithError:(NSError *)error {
```

#### Expected Behavior

I expect the CallKit call to end when the caller hangs up

#### Actual Behavior

The CallKit call continues despite the caller having dropped from the call

#### Reproduces How Often

100%

#### Logs

```
N/A
```

#### Voice iOS SDK

Twilio iOS SDK Framework 2.0.1

#### Xcode

Version 9.2 (9C40b)

#### iOS Version

11.2.1

#### iOS Device

iPad Mini 4

**Comment by bobiechen-twilio** [comment]
Hi @ariveraati 

Thanks for reporting the issue with the detailed descriptions.
I've tried the CallKit quickstart with the same steps but I was able to see the call to end on the mobile client side when the caller hung up. Maybe my steps are somehow different?
1. run the CallKit quickstart (identity `A`)
2. background the app (should be still alive)
3. make a call from another client to `A`
4. phone rings on `A`, and accept the call
5. being brought into the app once accepted
6. caller hang up, and the call is disconnected properly on `A`

**Comment by ariveraati** [comment]
Thanks for the quick reply @bchen-twilio. Can you try the same steps except with the screen off so the app does not take over from the native callkit interface?

**Comment by bobiechen-twilio** [comment]
I tried using the lock button to turn off the screen once the app is launched and registered (w/out backgrounding the app tho). Still able to get the disconnect callback properly.

**Comment by ariveraati** [comment]
My apologies. I was able to get it to work under those conditions as well. It is **not** working if the app is backgrounded and the screen is off. Can you try that scenario?

**Comment by ariveraati** [comment]
```
Mar  1 06:52:53 [665] <Notice>: Call disconnected
Mar  1 06:52:53 (CFNetwork)[665] <Notice>: TIC TCP Conn Start [115:0x1c016bd00]
Mar  1 06:52:53 <Notice>: Call Did Disconnect: <TVOCall: 0x1c01336a0>
Mar  1 06:52:53 (CFNetwork)[665] <Notice>: Task <61E65D41-A524-4E29-AE83-0424BD7F8A4B>.<3> setting up Connection 115
Mar  1 06:52:53 <Notice>: transaction: <private>
Mar  1 06:52:53 <Notice>: callControllerHostConnection: <private> transaction: <private> extensionIdentifier: (null)
Mar  1 06:52:53 <Notice>: Call controller host <private> requested transaction <private> for connection with identifier: <private> bundle: <private> extensionIdentifier: (null)
Mar  1 06:52:53 <Notice>: Using call source <private> for requested transaction <private>
Mar  1 06:52:53 <Notice>: [WARN] Not allowing requested transaction because no call was found for call UUID <private> and call source <private>. All calls: <private>
Mar  1 06:52:53 <Notice>: [WARN] Not allowing requested transaction: <private>
Mar  1 06:52:53 (CallKit)[665] <Notice>: Received reply from transaction request with error: <private>
Mar  1 06:52:53 <Notice>: EndCallAction transaction request failed: The operation couldn\M-b\M^@\M^Yt be completed. (com.apple.CallKit.error.requesttransaction error 4.)
```
For some reason the UUID is not found and the termination fails. This could be due to some changes I made to the demo app. I'll keep digging. Thank you!

**Comment by ariveraati** [comment]
I wonder if it has anything to do with how the call is answered through CallKit. See below:
```
- (void)performAnswerVoiceCallWithUUID:(NSUUID *)uuid
                            completion:(void(^)(BOOL success))completionHandler {

    self.call = [self.callInvite acceptWithDelegate:self];
    self.callInvite = nil;
    self.callKitCompletionCallback = completionHandler;
}
```
that gets called by this:
```
- (void)provider:(CXProvider *)provider performAnswerCallAction:(CXAnswerCallAction *)action {
    NSLog(@"provider:performAnswerCallAction:");
    
    // RCP: Workaround from https://forums.developer.apple.com/message/169511 suggests configuring audio in the
    //      completion block of the `reportNewIncomingCallWithUUID:update:completion:` method instead of in
    //      `provider:performAnswerCallAction:` per the WWDC examples.
    // [[TwilioVoice sharedInstance] configureAudioSession];
    
    NSAssert([self.callInvite.uuid isEqual:action.callUUID], @"We only support one Invite at a time.");
    
    TwilioVoice.audioEnabled = NO;
    [self performAnswerVoiceCallWithUUID:action.callUUID completion:^(BOOL success) {
        if (success) {
            [action fulfill];
        } else {
            [action fail];
        }
    }];
    
    [action fulfill];
}
```
It is passing the UUID of the call but `performAnswerVoiceCallWithUUID` is not doing anything with it. Is that right?

**Comment by ariveraati** [comment]
Let me know if I understand the flow correctly:

1. TVONotificationDelegate callInviteReceived
2. self reportIncomingCallFrom
3. callKitProvider reportNewIncomingCallWithUUID
4. CXProvider performAnswerCallAction
5. self performAnswerVoiceCallWithUUID
6. self.call = [self.callInvite acceptWithDelegate:self];
7. TVOCallDelegate didDisconnectWithError
8. [self performEndCallActionWithUUID:call.uuid]
9. CXEndCallAction *endCallAction = [[CXEndCallAction alloc] initWithCallUUID:uuid];
    CXTransaction *transaction = [[CXTransaction alloc] initWithAction:endCallAction];

On number 9, ending the call fails. But **ONLY** if the app is backgrounded and the screen is off.

**Comment by ariveraati** [comment]
Hm. I wonder. Between numbers 6 and 7, is TVOCallDelegate callDidConnect fired? It overwrites the `self.call` object. Perhaps the call from that event has a different UUID?

**Comment by ariveraati** [comment]
I re-deployed the app, and it is working now. I am not sure what happened, but it may have been related to how I was handling outgoing calls and the callkit integration.

**Comment by bobiechen-twilio** [comment]
Hi @ariveraati 

Glad that things are working now!
Please feel free to reach out to the team if you run into any issue in the future and we are more than happy to help.

-bobie
