### ISSUE TITLE
An error When Adding a push credential

### ISSUE THREAD

**Issue by allenming123** [twilio/voice-quickstart-objc#90]
**Setp8. Create a Push Credential with your VoIP Service Certificate**

> Go to the Push Credentials page and create a new Push Credential.

When I follow this instruction, I got an error as follow:
There was a problem attempting to create a new Push Credential: Could not parse certificate

BTW I did paste the content as plain text

**Comment by bobiechen-twilio** [comment]
Hi @allenming123 

I am assuming that you've already figured out and got the push credential to work but I am still interested in knowing in case the instructions in the README is out of sync with the Push Credential configuration console.

Thanks!
-bobie

**Comment by allenming123** [comment]
It is my mistake, the instruction issufficient.


I just miss the-----BEGIN CERTIFICATE-----and-----END CERTIFICATE-----part.


😂


原始邮件
发件人:bchen-twilionotifications@github.com
收件人:twilio/voice-quickstart-objcvoice-quickstart-objc@noreply.github.com
抄送:allenming123allen.ming@musjoy.com; Mentionmention@noreply.github.com
发送时间:2018年3月2日(周五) 02:23
主题:Re: [twilio/voice-quickstart-objc] An error When Adding a pushcredential (#90)


Hi @allenming123
I am assuming that you've already figured out and got the push credential to work but I am still interested in knowing in case the instructions in the README is out of sync with the Push Credential configuration console.
Thanks!
 -bobie

**Comment by NatashaApporio** [comment]
I am getting error while adding Push Credential

![Screen Shot 2019-06-26 at 5 18 03 PM](https://user-images.githubusercontent.com/43563955/60177700-2b625a80-9837-11e9-9812-4c124c56df2e.png)
 There was a problem attempting to create a new Push Credential: Could not parse certificate

**Comment by bobiechen-twilio** [comment]
Hi @NatashaApporio,

Could you please check the guides [here](https://github.com/twilio/voice-quickstart-objc#7-create-voip-service-certificate) and [here](https://github.com/twilio/voice-quickstart-objc#8-create-a-push-credential-with-your-voip-service-certificate) and make sure you are using a valid Apple VoIP certificate for creating the Push Credential?

Thanks,
-bobie

**Comment by NatashaApporio** [comment]
HI @bchen-twilio ,

Actually the creation of .pem file was incorrect . Thanks for responding .
