### ISSUE TITLE
Calls default to speaker, even when headphones are plugged in

### ISSUE THREAD

**Issue by ariveraati** [twilio/voice-quickstart-objc#92]
### Description

It appears that this example toggles the speaker phone on by default for incoming and outgoing calls. 

### Steps to Reproduce

1. Place a call using the demo app
2. Plugin headphones and verify audio is routing through the headphones
3. End the call
4. Place a new call and observe that audio is now routing through the speaker rather than the plugged in headphones

#### Code

```objc
- (void)provider:(CXProvider *)provider performStartCallAction:(CXStartCallAction *)action {
    NSLog(@"provider:performStartCallAction:");

    [TwilioVoice configureAudioSession];
    [self toggleAudioRoute:YES];
    TwilioVoice.audioEnabled = NO;
    
    [self.callKitProvider reportOutgoingCallWithUUID:action.callUUID startedConnectingAtDate:[NSDate date]];
    
    TwilioVoicePlugin __weak *weakSelf = self;
    [self performVoiceCallWithUUID:action.callUUID client:nil completion:^(BOOL success) {
        TwilioVoicePlugin __strong *strongSelf = weakSelf;
        if (success) {
            [strongSelf.callKitProvider reportOutgoingCallWithUUID:action.callUUID connectedAtDate:[NSDate date]];
            [action fulfill];
        } else {
            [action fail];
        }
    }];
}

- (void)reportIncomingCallFrom:(NSString *) from withUUID:(NSUUID *)uuid {
    CXHandle *callHandle = [[CXHandle alloc] initWithType:CXHandleTypeGeneric value:from];
    
    CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
    callUpdate.remoteHandle = callHandle;
    callUpdate.supportsDTMF = YES;
    callUpdate.supportsHolding = YES;
    callUpdate.supportsGrouping = NO;
    callUpdate.supportsUngrouping = NO;
    callUpdate.hasVideo = NO;
    
    [self.callKitProvider reportNewIncomingCallWithUUID:uuid update:callUpdate completion:^(NSError *error) {
        if (!error) {
            NSLog(@"Incoming call successfully reported.");
            
            // RCP: Workaround per https://forums.developer.apple.com/message/169511
            [TwilioVoice configureAudioSession];
            [self toggleAudioRoute:YES];
        }
        else {
            NSLog(@"Failed to report incoming call successfully: %@.", [error localizedDescription]);
        }
    }];
}
```

#### Expected Behavior

I would expect that the audio would route through the headphones because they are plugged into the device.

#### Actual Behavior

Audio routes to the speaker despite headphones being plugged in. This requires unplugging and plugging in the headphones with each new call.

#### Reproduces How Often

100%

#### Logs

N/A

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

2.0.1 Framework

#### Xcode

Version 9.2 (9C40b)

#### iOS Version

11.2.1

#### iOS Device

iPad Mini 4

**Comment by bobiechen-twilio** [comment]
Hi @ariveraati 

Please remove the `[self toggleAudioRoute:YES];` line where calls get reported so the application doesn't override the default audio route.

Thanks.
-bobie

**Comment by ariveraati** [comment]
That worked without issue. Thanks!
