### ISSUE TITLE
Can not create a Push Credential

### ISSUE THREAD

**Issue by allenming123** [twilio/voice-quickstart-objc#93]
Yesterday, I create a push credential. 

Today, I delete it, and want create a new one.

when I have filled the blanks, and clicked the save button.

I just redirect to the previous page. nothing add.

P.S. My account is a trial account.

**Comment by allenming123** [comment]
And it seems no mater what i fill with all three blanks,
It just redirect me to this page:
https://www.twilio.com/console/voice/sdks/credentials

and did nothing, because nothing added.

**Comment by bobiechen-twilio** [comment]
Hi @allenming123 

Sorry that you are experiencing some technical issue with the developer console, but without your account credential I am afraid we can't help much here. If you are still seeing the same problem, please go to Twilio Support and file a ticket with you account SID so we can use the credential to see if we can find out anything unusual. You may as well mention "Bobie from the Voice SDK team" so our support engineers know to forward the issue directly to the team.

One thing I am curious is that are you seeing any error message popping out in the console when you clicked the save button?

Thanks
-bobie

**Comment by allenming123** [comment]
ACCOUNT SID: AC0305d404dd2af5ca883cc1d8de7ce1bc


no error at all, when i clicked save button, it just redirect me to the following page:
https://www.twilio.com/console/voice/sdks/credentials


原始邮件
发件人:bchen-twilionotifications@github.com
收件人:twilio/voice-quickstart-objcvoice-quickstart-objc@noreply.github.com
抄送:allenming123allen.ming@musjoy.com; Mentionmention@noreply.github.com
发送时间:2018年3月7日(周三) 07:12
主题:Re: [twilio/voice-quickstart-objc] Can not create a Push Credential(#93)


Hi @allenming123
Sorry that you are experiencing some technical issue with the developer console, but without your account credential I am afraid we can't help much here. If you are still seeing the same problem, please go to Twilio Support and file a ticket with you account SID so we can use the credential to see if we can find out anything unusual. You may as well mention "Bobie from the Voice SDK team" so our support engineers know to forward the issue directly to the team.
One thing I am curious is that are you seeing any error message popping out in the console when you clicked the save button?
Thanks
 -bobie

**Comment by bobiechen-twilio** [comment]
Hi @allenming123 

I've passed the info to the Notify team and am waiting for their help to see if they can find any anomaly regarding your attempt to create the push credential.
Please stay tuned.

Thanks
-bobie

**Comment by bobiechen-twilio** [comment]
Hi @allenming123 

It appeared to be a bug in https://www.twilio.com/console/voice/sdks/credentials. The console team has identified the issue and updated. Could you please try again and let us know if you are able to create Push Credentials again.

Thanks and sorry for the inconvenience.
-bobie

**Comment by allenming123** [comment]
@bchen-twilio The problem is settled, thanks!
